### ISSUE TITLE
Add tree - "Uncaught TypeError: t is null"

### ISSUE THREAD

**Issue by asg7443** [umonkey/treemap#62]
Hi!

I get a blank screen and "Uncaught TypeError: t is null" in desktop Firefox's console after clicking "Add tree" button under authenticated account.
[console-export-2024-5-12_12-31-54.txt](https://github.com/umonkey/treemap/files/15285566/console-export-2024-5-12_12-31-54.txt)
 
After signing off from account "Add tree" starts to display correctly.

On mobile Firefox and Chrome behavior is the same, at least visually.

**Comment by umonkey** [comment]
@asg7443 please see if you can still reproduce this?

**Comment by asg7443** [comment]
No, now I get the dialog in all three browsers.
Thanks!
