### ISSUE TITLE
Try replacing clusters with hexbin?

### ISSUE THREAD

**Issue by umonkey** [umonkey/treemap#78]
Hexbin seems a little faster on phones.

About: https://geo.rocks/post/leaflet-hexbins/
Demo: https://jsfiddle.net/ou3rewnb/3/

**Comment by Gregory108** [comment]
Greptile:

> To replace cluster bubbles with hexbins, you'll need to make significant changes to the current implementation. The `MarkerCluster` component is currently using the `react-leaflet-cluster` library, which doesn't natively support hexbin clustering. Here's a general approach to implement hexbin clustering:
> 
> 1. Remove the `react-leaflet-cluster` dependency and its usage in `MarkerCluster.tsx`.
> 
> 2. Install and use a hexbin clustering library. A popular choice is `d3-hexbin`, which can be used with Leaflet.
> 
> 3. Rewrite the `MarkerCluster` component to use hexbin clustering. Here's a basic outline of how you might structure this:
> 
> ```tsx
> import React, { useEffect } from 'react';
> import { useLeaflet } from 'react-leaflet';
> import L from 'leaflet';
> import * as d3 from 'd3';
> import 'd3-hexbin';
> 
> interface IProps {
>   children: React.ReactNode | React.ReactNode[];
> }
> 
> export const HexbinCluster = (props: IProps) => {
>   const { map } = useLeaflet();
> 
>   useEffect(() => {
>     if (!map) return;
> 
>     // Create a hexbin layer
>     const hexLayer = L.hexbinLayer({
>       radius: 20,
>       opacity: 0.5,
>       // Add more options as needed
>     }).addTo(map);
> 
>     // Add data to the hexbin layer
>     // You'll need to extract coordinates from props.children
>     const data = extractDataFromChildren(props.children);
>     hexLayer.data(data);
> 
>   }, [map, props.children]);
> 
>   return null; // The hexbin layer is added directly to the map
> };
> 
> function extractDataFromChildren(children) {
>   // Implement this function to extract coordinate data from children
> }
> ```
> 
> 4. You'll need to implement the `extractDataFromChildren` function to get the coordinates of all markers from the `children` prop.
> 
> 5. Adjust the hexbin options (like radius, opacity, color scale) to match your desired appearance.
> 
> 6. Update any parent components that were using `MarkerCluster` to use your new `HexbinCluster` component instead.
> 
> Please note that this is a significant change from the current implementation and will require careful testing and potentially adjustments to other parts of your application that interact with the map and markers.
> 
> Also, keep in mind that hexbin clustering might not be a direct replacement for marker clustering in all use cases. It's typically used for density visualization rather than grouping individual markers. Make sure this change aligns with your application's requirements and user experience goals.

So.... I'm afraid those changes are too big for me to do without test environment.

**Comment by umonkey** [comment]
Implemented custom clustering with a fixed 10x10 grid.
