### ISSUE TITLE
Exclude table `users` from the database dump

### ISSUE THREAD

**Issue by ShoshinNikita** [umonkey/treemap#96]
Table `users` contains sensitive data such as email and name. I'm not sure it's a good idea to include this information in the publicly available database dump.

![image](https://github.com/user-attachments/assets/b908d828-f71a-4420-ae04-d2087e03c184)

**Comment by Gregory108** [comment]
@umonkey 
I think, this is the most important feature at this stage. Without it I cannot tell the world (I know of the similar tree-protection movement in Argentina) about the database and even cannot in good consciousness say people it is safe to do what we do. Participants' data must be protected (and deleted from earlier dumps) as per GDPR.

- [ ] as a stilt, limit access to the daily dumps only to you and me
- [ ] remove PII form newly generated database dumps
- [ ] remove PII from historic dumps on Dropbox

What is necessary for that feature?

**Comment by umonkey** [comment]
Since the users table doesn't contain any other information than what was considered private, I just removed the whole table from the dumps.  New dumps don't have this table.  Old dumps were deleted.  We have the history of changes in the database, so a history of dumps is not needed.
